#!/bin/sh

#art
printf "\n\n"
/home/zoe/lol/nanoarch


#scripting
colls=$(tput cols)
center() {
collsp=$(($colls-${#current}))
collspace=$(($collsp/2))
i=0
while [ $((i+=1)) -le $collspace ]; do
     printf " %.0s" "$i"
done
}
memorytotal=$(free -m | grep -o "[0-9]*" | head -n 1)
memoryused=$(free -m | grep -o "[0-9]*" | head -n 2 | tail -1)
w="[0;39m"
c="[1;34m"
x="[1;39m x"



#setting things
user="=+= $USER =+="
os="echo $(uname -r | grep -o "\-*...." | tail -n 1 | awk '{print tolower($0)}')"
wm="wm x $GDMSESSION"
terminal="terminal x $(xprop -id `xdotool getwindowfocus`| grep WM_CLASS\(STRING\) | grep -o "\"[A-Za-z0-9]*\"" | grep -o "[A-Za-z0-9]*" | head -n 1)"
cpu="cpu x$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | cut -d':' -f2 | sed -e s/"\ [a-zA-Z0-9]*-[cC]ore.*"//g -e s/"(tm)"//g)"
gpu="gpu x $(lspci | grep VGA | grep -o "\[.*\]" | cut -d'/' -f3 | cut -d'[' -f2)"
memory="memory x$memoryused mib / $memorytotal mib"
colorblocks="████████"


#info
usertxt="$w=+=$c $USER $w=+="
ostxt="os$x$c $(uname -r | grep -o "\-*...." | tail -n 1 | awk '{print tolower($0)}')$w"
wmtxt="wm$x$c $GDMSESSION$w"
terminaltxt="$w terminal$x$c $(xprop -id `xdotool getwindowfocus`| grep WM_CLASS\(STRING\) | grep -o "\"[A-Za-z0-9]*\"" | grep -o "[A-Za-z0-9]*" | head -n 1)$w"
cputxt="cpu$x$c$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | cut -d':' -f2 | sed s/\(tm\)//g | sed -e s/"\ [a-zA-Z0-9]*-[C]ore.*"//g -e s/"(tm)"//g | awk '{print tolower($0)}')$w"
gputxt="gpu$x$c $(lspci | grep VGA | grep -o "\[.*\]" | cut -d'/' -f3 | cut -d'[' -f2 | awk '{print tolower($0)}')$w"
memorytxt="memory$x $c$memoryused mib / $memorytotal mib"
colorblockstxt="[1;30m█[1;31m█[1;32m█[1;33m█[1;34m█[1;35m█[1;36m█[1;37m█"



#newlines
printf "\n\n"

#print username
current=$user
center
printf "$c$usertxt\n"

#print OS
current=$os
center
printf "$ostxt\n"

#print WM
current=$wm
center
printf "$wmtxt\n"

#print terminal
current=$terminal
center
printf "$terminaltxt\n"

#print CPU
current=$cpu
center
printf "$cputxt\n"

#print GPU
current=$gpu
center
printf "$gputxt\n"

#print memory
current=$memory
center
printf "$memorytxt\n\n"

#print colors
current=$colorblocks
center
printf "$colorblockstxt\n"
