#!/bin/bash
echo enter username
read user
echo enter OS
read os
echo enter WM
read wm
echo enter terminal
read terminal
echo enter font
read font
echo enter cpu
read cpu
echo enter gpu
read gpu
echo enter desired location of nanoarch text file, full path no  "~"
read nanolocation
cp ./nanoarch $nanolocation/nanoarch

sed "s|\[ARTPATH]|$nanolocation/nanoarch|g
s/\[USERNAME]/$user/g
s/\[OS]/$os/g
s/\[WM]/$wm/g
s/\[TERMINAL]/$terminal/g
s/\[FONT]/$font/g
s/\[CPU]/$cpu/g
s/\[GPU]/$gpu/g" pseudotemplate > pseudofetch
chmod +x pseudofetch
