#!/bin/zsh
#scripting
colls=$(tput cols)
center() {
collsp=$(expr $colls - ${#current})
collspace=$(expr $collsp / 2)
printf ' %.0s' {1..$collspace}
}
memorytotal=$(free -m | grep -o "[0-9]*" | head -n 1)
memoryused=$(free -m | grep -o "[0-9]*" | head -n 2 | tail -1)
w="\e[1;39m"
c="\e[1;34m"
x="\e[1;39m x"
#art
[ARTPATH]
#info
user="$w=+=$c [USERNAME] $w=+="
os="os$x$c [OS]$w"
wm="wm$x$c [WM]$w"
terminal="$w terminal$x$c [TERMINAL]$w"
font="font$x$c [FONT]$w"
cpu="cpu$x$c [CPU]$w"
gpu="gpu$x$c [GPU]$w"
memory="memory$x $c$memoryused MiB / $memorytotal MiB"

usertxt="=+= [USERNAME] =+="
ostxt="os x [OS]"
wmtxt="wm x [WM]"
terminaltxt="terminal x [TERMINAL]"
fonttxt="font x [FONT]"
cputxt="cpu x [CPU]"
gputxt="gpu x [GPU]"
memorytxt="memory x$memoryused MiB / $memorytotal MiB"

#out
#collsp=$(expr $colls - ${#os})
#collspace=$(expr $collsp / 2)


#newlines
printf '\n\n'

#print username
current=$usertxt
center
printf "$c$user\n"

#print OS
current=$ostxt
center
printf "$os\n"

#print WM
current=$wmtxt
center
printf "$wm\n"

#print terminal
current=$terminaltxt
center
printf "$terminal\n"

#print font
current=$fonttxt
center
printf "$font\n"

#print CPU
current=$cputxt
center
printf "$cpu\n"

#print GPU
current=$gputxt
center
printf "$gpu\n"

#print memory
current=$memorytxt
center
printf "$memory\n"
