#!/bin/sh
#scripting
colls=$(tput cols)
center() {
collsp=$(expr $colls - ${#current})
collspace=$(expr $collsp / 2)
i=0
while [ $((i+=1)) -le $collspace ]; do
     printf " %.0s" "$i"
done
}
memorytotal=$(free -m | grep -o "[0-9]*" | head -n 1)
memoryused=$(free -m | grep -o "[0-9]*" | head -n 2 | tail -1)
w="[1;39m"
c="[1;34m"
x="[1;39m x"
#art
printf "\n\n"
/home/zoe/lol/nanoarch

#Setting stuff


#setting things
usertxt="=+= $USER =+="
ostxt="echo $(uname -r | grep -o "\-*...." | tail -n 1 | awk '{print tolower($0)}')"
wmtxt="wm x $GDMSESSION"
terminaltxt="terminal x $(xprop -id `xdotool getwindowfocus`| grep WM_CLASS\(STRING\) | grep -o "\"[A-Za-z0-9]*\"" | grep -o "[A-Za-z0-9]*" | head -n 1)"
cputxt="cpu x$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | cut -d':' -f2 | sed -e s/"\ [a-zA-Z0-9]*-[cC]ore.*"//g -e s/"(tm)"//g)"
gputxt="gpu x $(lspci | grep VGA | grep -o "\[.*\]" | cut -d'/' -f3 | cut -d'[' -f2)"
memorytxt="memory x$memoryused mib / $memorytotal mib"
colorblockstxt="████████"
#out
#collsp=$(expr $colls - ${#os})
#collspace=$(expr $collsp / 2)

#info
user="$w=+=$c $USER $w=+="
os="os$x$c $(uname -r | grep -o "\-*...." | tail -n 1 | awk '{print tolower($0)}')$w"
wm="wm$x$c $GDMSESSION$w"
terminal="$w terminal$x$c $(xprop -id `xdotool getwindowfocus`| grep WM_CLASS\(STRING\) | grep -o "\"[A-Za-z0-9]*\"" | grep -o "[A-Za-z0-9]*" | head -n 1)$w"
cpu="cpu$x$c$(cat /proc/cpuinfo | grep 'model name' | head -n 1 | cut -d':' -f2 | sed s/\(tm\)//g | sed -e s/"\ [a-zA-Z0-9]*-[C]ore.*"//g -e s/"(tm)"//g | awk '{print tolower($0)}')$w"
gpu="gpu$x$c $(lspci | grep VGA | grep -o "\[.*\]" | cut -d'/' -f3 | cut -d'[' -f2 | awk '{print tolower($0)}')$w"
memory="memory$x $c$memoryused mib / $memorytotal mib"
colorblocks="[1;30m█[1;31m█[1;32m█[1;33m█[1;34m█[1;35m█[1;36m█[1;37m█"



#newlines
printf "\n\n"

#print username
current=$usertxt
center
printf "$c$user\n"

#print OS
current=$ostxt
center
printf "$os\n"

#print WM
current=$wmtxt
center
printf "$wm\n"

#print terminal
current=$terminaltxt
center
printf "$terminal\n"

#print CPU
current=$cputxt
center
printf "$cpu\n"

#print GPU
current=$gputxt
center
printf "$gpu\n"

#print memory
current=$memorytxt
center
printf "$memory\n\n"

#print colors
current=$colorblockstxt
center
printf "$colorblocks\n"
